name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Pacman graph
        uses: abozanona/pacman-contribution-graph@v1
        with:
          github_user_name: sethupathy03
          github_token: ${{ secrets.GITHUB_TOKEN }}
          theme: github-dark
          game: pacman
          output_folder: dist

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: pacman-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
